use_frameworks!

target 'RTSupportCode_Example' do
  pod 'RTSupportCode', :path => '../'

  target 'RTSupportCode_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
  pod 'Nimble', '~> 7.0.2'
  end
end
